artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/appsbotta/DataSets/raw/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

dataValidation:
  rootDir: artifacts/data_Validation
  statusFile: artifacts/data_Validation/status.txt
  allRequiredFiles: ['train','text','validation']

dataTransformation:
  rootDir: artifacts/data_transformation
  dataPath: artifacts/data_ingestion/samsum_dataset
  tokenizerName: google/pegasus-cnn_dailymail

modelTrainer:
  rootDir: artifacts/model_trainer
  dataPath: artifacts/data_transformation/samsumDataset
  modelCkpt: google/pegasus-cnn_dailymail
